# Earth

rotX = -66.56
rotY = -5.625 # 360 / 32 (lines) * 0.5
rotZ = 10

light_mode = "implicit"

light_pos_x = 0.6
light_pos_y = 0.8
light_pos_z = 5.0

# dark blue 65, 102, 174 | naphtol orange 240, 126, 50 | phthalo green 3, 168, 115 | chromium oxide green 174, 212, 164
colors = [[65, 102, 174], [240, 126, 50], [3, 168, 115]]
layer_colors = [[], [255, 255, 255], [], [255, 255, 255], [255, 255, 255]]
invert_background = true

dimensions = [699, 699]

[downloader]

# source: GEBCO https://www.gebco.net/data-products/gridded-bathymetry-data
dem_url = "https://dap.ceda.ac.uk/bodc/gebco/global/gebco_2025/ice_surface_elevation/geotiff/gebco_2025_geotiff.zip?download=1"
 
# source: https://visibleearth.nasa.gov/images/57730/the-blue-marble-land-surface-ocean-color-and-sea-ice
# surface_color_url = "https://eoimages.gsfc.nasa.gov/images/imagerecords/57000/57730/land_ocean_ice_8192.png"

# source: https://www.shadedrelief.com/natural3/pages/textures.html
surface_color_url = "http://shadedrelief.com/natural3/ne3_data/16200/textures/2_no_clouds_16k.jpg"

clouds_download = true
clouds_datetime = "2025-07-01 00:00"

[modify_dem_stage1]

resize_width = 15000

[modify_dem_stage2]

blur = 0.10
floor = 1.0

[modify_surfacecolor]

resize_width = 10000
convert_uint8 = true

[adjust_scene]

horizontal_width = 2.4
camera_focal_length = 30.0

light_size = 0.01
light_power = 250

[mesh]

scale = 0.09
subdivision = 10

[import_ply]

[overlay_pois]

circle_radius = 0.010
double_circle_radius = 0.0085
font_size = 0.017

[overlay_grid]

grid_lines_lat = 16
grid_lines_lon = 8

[overlay_axis]

axis_extent = [1.8, 1.18]

[overlay_contours]

offset = 0.005
double_line_distance = 0.0015

[process_blender]

mixture = [0.03, 0.07]

clip_lower_percent_range = 1.0
clip_upper_percent_range = 99.0

[palette]

[hatch]

blur_angle_kernel_size = 0 # 0.40
blur_distance_kernel_size = 0 # 0.40

flowlines_line_distance = [0.7, 10.0]
flowlines_line_min_length = 3
flowlines_line_max_length = [3, 20]
flowlines_line_distance_end_factor = 0.3
flowlines_max_angle_discontinuity = 1.57 # pi/2

[combine]

blur_color_kernel_size = 0.00

[modify_tiff_clouds]

scaling_factor = 1.0
#threshold = 210

[mesh_clouds]

scale = 0.05
fixed_elevation_scale = 1.0
subdivision = 10

[import_ply_clouds]

[overlay_coastlines]

radius = 1.2

[overlay_clouds]

threshold = 200

[overlay_clouds_hatch]

flowlines_line_distance = [1.0, 10.0]
flowlines_line_max_length = [30, 30]
flowlines_line_distance_end_factor = 0.5
flowlines_max_angle_discontinuity = 1.57 # pi/2
