rotX = -66.56
rotY = 0
rotZ = 10

light_angle_xy = 67.5
light_angle_z = 90 #50

# dark blue 65, 102, 174 | naphtol orange 240, 126, 50 | phthalo green 3, 168, 115 | chromium oxide green 174, 212, 164
colors = [[65, 102, 174], [240, 126, 50], [3, 168, 115]]
# layer_colors = [[], [], [255, 255, 255]]
layer_colors = [[], [255, 255, 255], [], [255, 255, 255], [255, 255, 255]]
invert_background = true

dimensions = [750, 750]

[downloader]

# source: GEBCO
dem_url = ""

# source: https://visibleearth.nasa.gov/images/57730/the-blue-marble-land-surface-ocean-color-and-sea-ice
surface_color_url = "https://eoimages.gsfc.nasa.gov/images/imagerecords/57000/57730/land_ocean_ice_8192.png"

clouds_download = true
clouds_datetime = "2025-07-01 00:00"

[modify_tiff]

scaling_factor = 0.25
floor = 0

[adjust_camera]

horizontal_width = 2.2
camera_focal_length = 30.0
resolution_x = 1000
resolution_y = 1000

[mesh]

scale = 0.10
subdivision = 10

[import_ply]

[overlay_pois]

circle_radius = 0.015
font_size = 0.020

[overlay_grid]

grid_lines_lat = 16
grid_lines_lon = 8

[overlay_axis]

axis_extent = 1.5

[process_blender]

mixture = [0.03, 0.07]

[palette]

[hatch]

blur_angle_kernel_size_perc = 0 # 0.40
blur_distance_kernel_size_perc = 0 # 0.40

flowlines_line_distance = [0.6, 8.0]
flowlines_line_max_length = [30, 30]
flowlines_line_distance_end_factor = 0.5
flowlines_max_angle_discontinuity = 1.57 # pi/2

[combine]

blur_color_kernel_size_perc = 0.00

[modify_tiff_clouds]

scaling_factor = 1.0
#threshold = 210

[mesh_clouds]

scale = 0.05
fixed_elevation_scale = 1.0
subdivision = 10

[import_ply_clouds]

[overlay_coastlines]

radius = 1.2

[overlay_clouds]

threshold = 200

[overlay_clouds_hatch]

flowlines_line_distance = [1.0, 10.0]
flowlines_line_max_length = [30, 30]
flowlines_line_distance_end_factor = 0.5
flowlines_max_angle_discontinuity = 1.57 # pi/2
