# Jupiter

rotX = -90
rotY = 0
rotZ = 0

light_mode = "implicit"

colors = [[240, 126, 50], [65, 102, 174]]

dimensions = [699, 699]

[downloader]

dem_url = ""

# source: https://bjj.mmedia.is/data/jupiter_css/index.html
surface_color_url = "https://bjj.mmedia.is/data/jupiter_css/jupiter_css.jpg"

[modify_dem_stage1]

resize_width = 15000

[modify_dem_stage2]

blur = 0.25

[modify_surfacecolor]

resize_width = 10000
convert_uint8 = true

[adjust_scene]

horizontal_width = 2.4
camera_focal_length = 50.0

[mesh]

scale = 0.04
subdivision = 10

[import_ply]

[overlay_pois]

circle_radius = 0.010
double_circle_radius = 0.0085
font_size = 0.017

[overlay_grid]

grid_lines_lat = 16
grid_lines_lon = 8

[overlay_axis]

[overlay_contours]

offset = 0.005
double_line_distance = 0.0015

[process_blender]

mixture = [0.03, 0.07]

[palette]

[hatch]

blur_angle_kernel_size = 0.40
blur_distance_kernel_size = 0.40

flowlines_line_distance = [0.6, 12.0]
flowlines_line_max_length = [30, 30]
flowlines_line_distance_end_factor = 0.5
flowlines_max_angle_discontinuity = 1.57 # pi/2

[combine]