rotX = -90
rotY = 0
rotZ = 0

light_angle_xy = 67.5
light_angle_z = 90 #50

colors = [[240, 126, 50], [65, 102, 174]]

[downloader]

dem_url = ""

# source: https://bjj.mmedia.is/data/jupiter_css/index.html
surface_color_url = "https://bjj.mmedia.is/data/jupiter_css/jupiter_css.jpg"

[modify_tiff]

scaling_factor = 1.0

[adjust_camera]

horizontal_width = 2.2
camera_focal_length = 50.0

[mesh]

scale = 0.04
subdivision = 10

[import_ply]

[overlay_pois]

circle_radius = 0.015
font_size = 0.020

[overlay_grid]

grid_lines_lat = 16
grid_lines_lon = 8

[overlay_axis]

[process_blender]

mixture = [0.03, 0.07]

[palette]

[hatch]

dimensions = [750, 750]

blur_color_kernel_size_perc = 0.00
blur_angle_kernel_size_perc = 0.40
blur_distance_kernel_size_perc = 0.40

flowlines_line_distance = [0.6, 12.0]
flowlines_line_max_length = [30, 30]
flowlines_line_distance_end_factor = 0.5
flowlines_max_angle_discontinuity = 1.57 # pi/2

[combine]