rotX = -90
rotY = 84.375 # 360 / 32 * 7.5  (32 lines in total, 7.5 to be in between)
rotZ = -22.5

light_angle_xy = 67.5
light_angle_z = 90 #50

colors = [[240, 126, 50], [65, 102, 174]]
invert_background = true

dimensions = [650, 650]

[downloader]

## source: https://astrogeology.usgs.gov/search/map/mars_mgs_mola_dem_463m
#dem_url = "https://planetarymaps.usgs.gov/mosaic/Mars_MGS_MOLA_DEM_mosaic_global_463m.tif"

## source: https://hrscteam.dlr.de/public/data/globalcolor.php
#surface_color_url = "https://hrscteam.dlr.de/public/data/global_mosaic/extra/globalmosaic.rgb.tif"

# source: https://astrogeology.usgs.gov/search/map/mars_mgs_mola_mex_hrsc_blended_dem_global_200m
dem_url = "https://planetarymaps.usgs.gov/mosaic/Mars/HRSC_MOLA_Blend/Mars_HRSC_MOLA_BlendDEM_Global_200mp_v2.tif"

# source: https://astrogeology.usgs.gov/search/map/mars_viking_global_color_mosaic_925m
surface_color_url = "https://planetarymaps.usgs.gov/mosaic/Mars_Viking_ClrMosaic_global_925m.tif"

[modify_tiff]

scaling_factor = 0.25

[adjust_scene]

horizontal_width = 2.2
camera_focal_length = 25.0

light_pos_x = 1.0
light_pos_y = 0.1
light_pos_z = 3.0
light_size = 0.2
light_power = 100

[mesh]

scale = 0.04
subdivision = 10

[import_ply]

[overlay_pois]

circle_radius = 0.012
font_size = 0.018
ignore_paths = true

[overlay_grid]

grid_lines_lat = 16
grid_lines_lon = 8

[overlay_axis]

[overlay_contours]

[process_blender]

mixture = [0.03, 0.07]

[palette]

[hatch]

blur_color_kernel_size_perc = 0.0
blur_angle_kernel_size_perc = 0.0
blur_distance_kernel_size_perc = 0.40

flowlines_line_distance = [0.6, 12.0]
flowlines_line_min_length = 6.0
flowlines_line_max_length = [20, 30]
flowlines_line_distance_end_factor = 1.0
flowlines_max_angle_discontinuity = 1.57 # pi/2

[combine]