# Moon

# -90 -5.14 lunar orbital inclination,
# see https://en.wikipedia.org/wiki/Orbit_of_the_Moon#/media/File:Lunar_Orbit_and_Orientation_with_respect_to_the_Ecliptic.svg

rotX = -95.14
rotY = -5.625 # 360 / 32 (lines) * 0.5
rotZ = -6.68 # axial tilt

# light_angle_xy = 83.32
# light_angle_z = 90

#light_axis_pos_x = 1.2
#light_axis_pos_y = 0.6
#light_axis_pos_z = 3.0

light_pos_x = 1.2
light_pos_y = 0.6
light_pos_z = 3.0

colors = [[255, 255, 255]]
layer_colors = [[245, 233, 94], [255, 255, 255]]
invert_background = true

dimensions = [698, 698]

[downloader]

dem_url = "https://planetarymaps.usgs.gov/mosaic/Lunar_LRO_LOLA_Global_LDEM_118m_Mar2014.tif"
surface_color_url = "https://svs.gsfc.nasa.gov/vis/a000000/a004700/a004720/lroc_color_poles.tif"

[modify_dem_stage1]

resize_width = 15000

[modify_dem_stage2]

blur = 0.25

[modify_surfacecolor]

resize_width = 10000
convert_uint8 = true
contrast_grid_size = 4
contrast_increase = 0.4

[adjust_scene]

horizontal_width = 2.4
camera_focal_length = 50.0
light_size = 0.01
light_power = 100

[mesh]

scale = 0.08
subdivision = 10

[import_ply]

[overlay_pois]

circle_radius = 0.010
double_circle_radius = 0.0085
font_size = 0.017

[overlay_grid]

grid_lines_lat = 16
grid_lines_lon = 8

[overlay_axis]

axis_extent = [1.17, 1.22]

[overlay_contours]
double_line_distance = 0.0015

[process_blender]

mixture = [0.04, 0.20]
contrast_increase = 0.5
clip_lower_percent_range = 1.0

[palette]

[hatch]

blur_color_kernel_size_perc = 0.0
blur_angle_kernel_size_perc = 0.0
blur_distance_kernel_size_perc = 0.40

flowlines_line_distance = [0.6, 8.0]
flowlines_line_min_length = 3
flowlines_line_max_length = [3, 25]
flowlines_line_distance_end_factor = 0.3
#flowlines_max_angle_discontinuity = 1.57 # pi/2
flowlines_max_angle_discontinuity = 0.78 # pi/4

[combine]

hatchlines_smoothing_iterations = 0
contours_smoothing_iterations = 5